### ISSUE TITLE
Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'Native.showAlertWithOptions')

### ISSUE THREAD

**Issue by metasanjaya** [Clip-sub/react-native-sweet-alert#9]
- node_modules/react-native-sweet-alert/index.js:26:11 in showAlertWithOptions
* src/components/screens/LoginScreen.js:33:36 in _callee$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:30 in invoke
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:152:28 in invoke
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:187:17 in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:186:27 in callInvokeWithMethodAndArg
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:209:38 in enqueue
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:233:8 in async
* src/components/screens/LoginScreen.js:32:12 in _callee
- node_modules/react-native/Libraries/Components/Touchable/TouchableOpacity.js:212:45 in touchableHandlePress
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:803:34 in _performSideEffectsForTransition
- ... 21 more stack frames from framework internals

**Comment by metasanjaya** [comment]
I follow all the steps on README, and I try it on Android

**Comment by avisaxena33** [comment]
I'm getting the same issue.

**Comment by khalilst** [comment]
Same for me, not working according to Readme.
There is no showAlert function only showAlertWithOptions and it says 
undefined is not an object (evaluating 'Native.showAlertWithOptions')

**Comment by khalilst** [comment]
I Think `index.js` ruined in this [commit](https://github.com/ducbka02/react-native-sweet-alert/commit/fb59fdf48ba091dc2703c5ca5f26bcaa9102894b#diff-168726dbe96b3ce427e7fedce31bb0bc).

**Comment by masesisaac** [comment]
Let me look into it, I will submit a PR as soon as I can

**Comment by glasje** [comment]
a mi me sale el siguiente error:
undefined is not a function (near'...reactNativeSweetAlert.default.showAlert...')
I am using expo and physical phone with android

**Comment by Doko-Demo-Doa** [comment]
Hello @metasanjaya 
Thanks for using the library. There was a mistake in README file, I have updated it.

This library might not work with Expo since it requires native module linking.

**Comment by khalilst** [comment]
@Doko-Demo-Doa The library doesn't work without Expo also. I've created an app with `react-native` and after installing and linking it wasn't worked.

**Comment by metasanjaya** [comment]
> @Doko-Demo-Doa The library doesn't work without Expo also. I've created an app with `react-native` and after installing and linking it wasn't worked.

That's right.. I've created with react-native, not expo...

And done `react-native link` as well...

**Comment by Doko-Demo-Doa** [comment]
Have you tried `SweetAlert.showAlertWithOptions` instead of `SweetAlert.showAlert`? I have updated the doc as well.

This is my retry on newly created project:

![Test](https://puu.sh/CEs3S.png)

**Comment by metasanjaya** [comment]
<img width="335" alt="screenshot 2019-01-30 at 4 49 36 pm" src="https://user-images.githubusercontent.com/239236/51972952-35ae4180-24af-11e9-9342-ac800ac1236f.png">

This is the screenshot, you can check the code here

https://github.com/metasanjaya/sweet-alert-react-native-example

Thank you

**Comment by Doko-Demo-Doa** [comment]
Oh I see, the code is a bit broken on Android due to the previous PR. I will re-check and update it ASAP.

**Comment by glasje** [comment]
@Doko-Demo-Doa 
Can you share the repo of the project you created?
It would be very helpful since I need to use the library

**Comment by Doko-Demo-Doa** [comment]
It is in the source code in this repo itself. The only problem is wrong method name.

**Comment by khalilst** [comment]
@Doko-Demo-Doa No, it is not the only problem.
It doesn't work with showAlertWithOptions.
I have the same issue like @metasanjaya .

**Comment by metasanjaya** [comment]
Hello, any updates?

**Comment by khalilst** [comment]
@metasanjaya I've started to create my own RN.SweetAlert

**Comment by metasanjaya** [comment]
> @metasanjaya I've started to create my own RN.SweetAlert

Can you share the code?

Thank you

**Comment by khalilst** [comment]
@metasanjaya  Yes, I'll do. Just too busy these days. ASAP I've put it in npm.

**Comment by sajadabasi** [comment]
I fixed this issue and created a pull request

**Comment by glasje** [comment]
![image](https://user-images.githubusercontent.com/34929785/58208379-9ce83f80-7cb2-11e9-8e8b-cad16c54c5ff.png)
I still have the same problem ... I'm not using expo-cli
upload the solution? if not to rule out this npm

**Comment by daytch** [comment]
any update on thhis case ? i have same trouble

**Comment by dxku** [comment]
For anyone reading this, I just had the same problem. You have to recompile the app (at least on android) in order to make it work. (: 

`react-native run-android`
